### ISSUE TITLE
文件乱码，导致打包的时候出错

### ISSUE THREAD

**Issue by goingta** [lichfy/fluwx_worker#1]
有些java文件乱码了，导致Android打包出错，类似ReflecterHelper.java文件

**Comment by lichfy** [comment]
不会啊，我自己项目中的依赖就引用的这里的git url。
发下详细信息

**Comment by goingta** [comment]
/Users/goingta/Documents/Work/flutter/.pub-cache/git/fluwx_worker-b45859f6b4565b5a7bac411f40d9ba243d6ecde4/android/src/main/java/com/tencent/wework/api/util/ReflecterHelper.java:24: 错误: 编码UTF-8的不可映射字符
         *            �������·��
                        ^
/Users/goingta/Documents/Work/flutter/.pub-cache/git/fluwx_worker-b45859f6b4565b5a7bac411f40d9ba243d6ecde4/android/src/main/java/com/tencent/wework/api/util/ReflecterHelper.java:24: 错误: 编码UTF-8的不可映射字符
         *            �������·��
                         ^
/Users/goingta/Documents/Work/flutter/.pub-cache/git/fluwx_worker-b45859f6b4565b5a7bac411f40d9ba243d6ecde4/android/src/main/java/com/tencent/wework/api/util/ReflecterHelper.java:24: 错误: 编码UTF-8的不可映射字符
         *            �������·��
                          ^
/Users/goingta/Documents/Work/flutter/.pub-cache/git/fluwx_worker-b45859f6b4565b5a7bac411f40d9ba243d6ecde4/android/src/main/java/com/tencent/wework/api/util/ReflecterHelper.java:24: 错误: 编码UTF-8的不可映射字符
         *            �������·��
                           ^
/Users/goingta/Documents/Work/flutter/.pub-cache/git/fluwx_worker-b45859f6b4565b5a7bac411f40d9ba243d6ecde4/android/src/main/java/com/tencent/wework/api/util/ReflecterHelper.java:24: 错误: 编码UTF-8的不可映射字符
         *            �������·��
                            ^
/Users/goingta/Documents/Work/flutter/.pub-cache/git/fluwx_worker-b45859f6b4565b5a7bac411f40d9ba243d6ecde4/android/src/main/java/com/tencent/wework/api/util/ReflecterHelper.java:24: 错误: 编码UTF-8的不可映射字符
         *            �������·��
                              ^
/Users/goingta/Documents/Work/flutter/.pub-cache/git/fluwx_worker-b45859f6b4565b5a7bac411f40d9ba243d6ecde4/android/src/main/java/com/tencent/wework/api/util/ReflecterHelper.java:24: 错误: 编码UTF-8的不可映射字符
         *            �������·��
                               ^
/Users/goingta/Documents/Work/flutter/.pub-cache/git/fluwx_worker-b45859f6b4565b5a7bac411f40d9ba243d6ecde4/android/src/main/java/com/tencent/wework/api/util/ReflecterHelper.java:25: 错误: 编码UTF-8的不可映射字符
         * @return �Ƿ����óɹ�
                   ^
/Users/goingta/Documents/Work/flutter/.pub-cache/git/fluwx_worker-b45859f6b4565b5a7bac411f40d9ba243d6ecde4/android/src/main/java/com/tencent/wework/api/util/ReflecterHelper.java:25: 错误: 编码UTF-8的不可映射字符
         * @return �Ƿ����óɹ�
                     ^
/Users/goingta/Documents/Work/flutter/.pub-cache/git/fluwx_worker-b45859f6b4565b5a7bac411f40d9ba243d6ecde4/android/src/main/java/com/tencent/wework/api/util/ReflecterHelper.java:25: 错误: 编码UTF-8的不可映射字符

**Comment by goingta** [comment]
你文件里面的那些注释都是乱码的

**Comment by lichfy** [comment]
哦，腾讯的sdk。我编译时候是警告，所以我就没理它
