### ISSUE TITLE
在Ipad上，flutter应用唤起企业微信登录后，点击”确认登录“之后还留在企业微信的首页。

### ISSUE THREAD

**Issue by xiangyu1225** [lichfy/fluwx_worker#4]
在Ipad上，flutter应用唤起企业微信登录后，点击”确认登录“之后还留在企业微信的首页，没有返回flutter应用，在ipad上这个功能可以用么？

使用了example中的代码，在调用fluwxWorker.isWeChatInstalled()时，打印出的结果是flutter: is installed false，跟这个有没有关系，但点击按钮是可以唤起企业微信的，点击”确认登录“之后还留在企业微信的首页。

**Comment by xiangyu1225** [comment]
Ipad上的这个应用还没有发布，点击”确认登录“之后还留在企业微信里跟这个会不会有关。确认 企业微信授权登录-IOS下的Bundle ID是我们的这个新应用。

**Comment by lichfy** [comment]
可能跟没有发布有关吧，ios比较麻烦，你试一下设置applinks看看

**Comment by xiangyu1225** [comment]
感谢回答，尝试了一下将applinks配置好了，Safari也可以打开app。
![image](https://user-images.githubusercontent.com/13384993/98240623-a6e42800-1fa4-11eb-8339-f0f27428a5fc.png)
但是在flutter唤起企业微信后点击登录还是留在了app内，并没有跳转回flutter应用。
![image](https://user-images.githubusercontent.com/13384993/98240677-bebbac00-1fa4-11eb-8753-f9abd2a0caf8.png)
![image](https://user-images.githubusercontent.com/13384993/98240734-d1ce7c00-1fa4-11eb-9b96-7a11177ae919.png)
能不能帮忙分析一下，可能是哪里弄错了。

**Comment by lichfy** [comment]
为当前app配过URLSchemes、LSApplicationQueriesSchemes这类吗？登录结束后没有把自己拉起来，停在企业微信界面了。

我主要Android开发的，iOS当时就是看着需要的在Info.plist里全加上

**Comment by xiangyu1225** [comment]
配置完URLSchemes可以把自己拉回来了，感谢。
